name: MLOps Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    outputs:
      accuracy: ${{ steps.metrics.outputs.accuracy }}
      f1: ${{ steps.metrics.outputs.f1 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[s3]

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Pull data from DVC
        run: dvc pull

      - name: Train model
        run: python src/train.py --model rf --max_depth 5 --features all

      - name: Extract Metrics
        id: metrics
        run: |
          ACC=$(jq '.accuracy' outputs/metrics.json)
          F1=$(jq '.f1_score' outputs/metrics.json)

          echo "accuracy=$ACC" >> $GITHUB_OUTPUT
          echo "f1=$F1" >> $GITHUB_OUTPUT


  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Compare Metrics
        id: compare
        run: |
          BEST_ACC=${{ vars.BEST_ACC }}
          BEST_F1=${{ vars.BEST_F1 }}

          echo "Previous Best Accuracy: $BEST_ACC"
          echo "New Accuracy: ${{ needs.train.outputs.accuracy }}"

          if (( $(echo "${{ needs.train.outputs.accuracy }} > $BEST_ACC" | bc -l) )) && \
             (( $(echo "${{ needs.train.outputs.f1 }} > $BEST_F1" | bc -l) )); then
            echo "improved=true" >> $GITHUB_OUTPUT
          else
            echo "improved=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if Not Improved
        if: steps.compare.outputs.improved == 'false'
        run: echo "Model not improved, skipping deployment"

      - name: Checkout code
        if: steps.compare.outputs.improved == 'true'
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: steps.compare.outputs.improved == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        if: steps.compare.outputs.improved == 'true'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/2022bcs0162-mlops .

      - name: Push Docker Image
        if: steps.compare.outputs.improved == 'true'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/2022bcs0162-mlops

      - name: Update Best Metrics
        if: steps.compare.outputs.improved == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh variable set BEST_ACC --body "${{ needs.train.outputs.accuracy }}"
          gh variable set BEST_F1 --body "${{ needs.train.outputs.f1 }}"